# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidStatusBoard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Charts'
  # Pods for CovidStatusBoard

  target 'CovidStatusBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovidStatusBoardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
